In [1]:
import numpy as np

Array shape

In [2]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [3]:
type(test_array[3])

numpy.float64

In [4]:
test_array.dtype

dtype('float64')

In [5]:
test_array.shape

(4,)

In [6]:
matrix  = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [7]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [8]:
np.array(tensor, int).size

48

In [9]:
np.array(tensor, int).ndim

3

.reshape()

In [10]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [11]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [12]:
test =np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [13]:
test.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

In [14]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

Indexing & Slicing

In [15]:
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
test_exmaple[0][0]

1

In [17]:
test_exmaple[0,0] = 10
test_exmaple

array([[10,  2,  3],
       [ 4,  5,  6]])

In [18]:
test_exmaple = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test_exmaple[:2,:] 

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

.arange()

In [19]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [20]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [21]:
matrix = np.arange(9).reshape(3, 3)
np.diag(matrix)

array([0, 4, 8])

Operation bwt arrays

In [22]:
array_a = np.array([[1,2,3],[4,5,6]], float)

In [23]:
print(array_a + array_a)
print(array_a * array_a)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [24]:
array_a = np.arange(1,7).reshape(2,3)
array_b = np.arange(7,13).reshape(3,2)
print(array_a.dot(array_b))

[[ 58  64]
 [139 154]]


In [25]:
array_a = np.arange(1,7).reshape(2,3)
scalar = 3
print(array_a + scalar)
print(array_a * scalar)

[[4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]]


Comparison operation

In [26]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

argument

In [27]:
a = np.array([1,2,4,5,8,78,23,3])
print(np.argmax(a), np.argmin(a))

5 0
